# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('book_isbn', models.CharField(max_length=25)),
                ('page', models.IntegerField(default=0)),
                ('no_of_copies', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('author', models.CharField(max_length=50)),
                ('tag', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='book_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book.Subject'),
        ),
    ]
